version: "3.9"

services:
  egdev-site:
    build: .
    container_name: egdev-site
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.egdev.rule=Host(`egdev.cloud`) || Host(`www.egdev.cloud`)"
      - "traefik.http.routers.egdev.entrypoints=https"
      - "traefik.http.routers.egdev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.egdev-http.rule=Host(`egdev.cloud`) || Host(`www.egdev.cloud`)"
      - "traefik.http.routers.egdev-http.entrypoints=http"
      - "traefik.http.routers.egdev-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.egdev.loadbalancer.server.port=80"

networks:
  coolify:
    external: true
